### ISSUE TITLE
Differentiation from competition?

### ISSUE THREAD

**Issue by amcgregor** [fe3dback/web-debug-proto#1]
Howdy!

I noticed you popping into `##webdev` on Freenode IRC yesterday, and was curious if you have evaluated the "competition", so to say?

* [Microsoft Edge Devtools Protocol](https://docs.microsoft.com/en-us/microsoft-edge/devtools-protocol/)
* [Firebug](https://getfirebug.com) (now Firefox developer tools) w/ such connectors as [FireLog](https://firelogger.binaryage.com) (though there are a number found when searching Pypi for `firebug`)
* [WDB](https://github.com/Kozea/wdb#readme) (the "web debugger", one of a class of remote debuggers)

Additionally, thoughts on HAR integration?  (Generation / import / export?)

Thanks!

**Comment by fe3dback** [comment]
Hi, many different protocols are exist at this moment, but general cons is compatibility between them.

Devtools developers make it compatible only for specific software or language, framework developers reinventing the wheel with own tools working only as html panel injected to site.

And clients like postman or curl not support any of them at all.

--

For example, many developers use frameworks like symfony, and symfony has own debug panel, but when them start working on API and going to postman from browser, possibility of quality debug is completly losed.

Main idea of this project is make protocol as simple as possible, working everywhere. So you can work on different languages and frameworks with same debug tools in your favorite environment and quick switch between them.

--

> Additionally, thoughts on HAR integration?
what is HAR?

**Comment by amcgregor** [comment]
> And clients like postman or curl not support any of them at all.

The addition of a new standard, sadly, won't change that, though.

> what is HAR?

[HTTP Archive](https://en.wikipedia.org/wiki/.har) containing a log of a web browser's interaction with a site.

**Comment by fe3dback** [comment]
Yep, but protocol can be implemented wia plugins. Currently i develop client side tool (like postman), but after release I plan to show this to postman developers. Supporting of chrome/edge devtools is not hard, browser extension can handle it.

**Comment by fe3dback** [comment]
> Additionally, thoughts on HAR integration? (Generation / import / export?)

No, this is not same protocol. Both protocols solve different problems.
